# Site settings
title: ece rocks
emails: [ "alex@kersten.email", "kenneth@siu.email" ]
description: > # this means to ignore newlines until "baseurl:"
 a blog about electrical and computer engineering
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ece.rocks" # the base hostname & protocol for your site
twitter_usernames: [ "amkersten", "kungsiupanda" ]
github_usernames:  [ "akersten", "kksiu" ]

# Build settings
markdown: kramdown
